In [1]:
import pandas as pd

per_game = 'NBA_2017_2018_Statistics.csv'
per_36min = 'NBA_2017_2018_Statistics_per_36 min.csv'
nba_salary = 'NBA_season17_18_salary.csv'

per_game = pd.read_csv(per_game)
per_36min = pd.read_csv(per_36min)
nba_salary = pd.read_csv(nba_salary)

per_game = pd.DataFrame(per_game)
per_36min = pd.DataFrame(per_36min)
nba_salary = pd.DataFrame(nba_salary)

In [2]:
per_game_df = pd.merge(per_game, nba_salary, on= "Player & Team", how="outer")
per_game_df = per_game_df.drop(columns=['Player & Team','Player_y', 'Team_y','ORB','DRB',
                                        '3P','3PA','3P%','2P','2PA','2P%','eFG%','FT','FTA'])
per_game_df = per_game_df.rename(columns={'Player_x':'Player','Team_x':'Team'})
per_game_df = per_game_df.dropna()

#82 Games in NBA season

per_game_df["Salary per Game"] = round(per_game_df["season17_18"]/82,2)
per_game_df.head()

,Player,Team,Pos,Age,G,GS,MP,FG,FGA,FG%,FT%,TRB,AST,STL,BLK,TOV,PF,PTS,season17_18,Salary per Game
0,Alex Abrines,OKC,SG,24.0,75.0,8.0,15.1,1.5,3.9,0.395,0.848,1.5,0.4,0.5,0.1,0.3,1.7,4.7,5725000.0,69817.07
1,Quincy Acy,BRK,PF,27.0,70.0,8.0,19.4,1.9,5.2,0.356,0.817,3.7,0.8,0.5,0.4,0.9,2.1,5.9,1709538.0,20848.02
2,Steven Adams,OKC,C,24.0,76.0,76.0,32.7,5.9,9.4,0.629,0.559,9.0,1.2,1.2,1.0,1.7,2.8,13.9,22471910.0,274047.68
3,Bam Adebayo,MIA,C,20.0,69.0,19.0,19.8,2.5,4.9,0.512,0.721,5.5,1.5,0.5,0.6,1.0,2.0,6.9,2490360.0,30370.24
4,Arron Afflalo,ORL,SG,32.0,53.0,3.0,12.9,1.2,3.1,0.401,0.846,1.2,0.6,0.1,0.2,0.4,1.1,3.4,2328652.0,28398.20

In [5]:
per_36min_df = pd.merge(per_36min, nba_salary, on= "Player & Team", how="outer")
per_36min_df = per_36min_df.drop(columns=['Player & Team','Player_y', 'Team_y','ORB','DRB',
                                        '3P','3PA','3P%','2P','2PA','2P%','FT','FTA'])
per_36min_df = per_36min_df.rename(columns={'Player_x':'Player','Team_x':'Team'})
per_36min_df = per_36min_df.dropna()

#82 games x 48 minutes per game = 3,936 minutes per game 

per_36min_df["Salary per min"] = round(per_36min_df["season17_18"]/3936,2)
per_36min_df["Salary per 36 min"] = per_36min_df["Salary per min"] * 36

per_36min_df.head()

,Player,Team,Pos,Age,G,GS,MP,FG,FGA,FG%,...,TRB,AST,STL,BLK,TOV,PF,PTS,season17_18,Salary per min,Salary per 36 min
0,Alex Abrines,OKC,SG,24.0,75.0,8.0,1134.0,3.7,9.2,0.395,...,3.6,0.9,1.2,0.3,0.8,3.9,11.2,5725000.0,1454.52,52362.72
1,Quincy Acy,BRK,PF,27.0,70.0,8.0,1359.0,3.4,9.7,0.356,...,6.8,1.5,0.9,0.8,1.6,3.9,10.9,1709538.0,434.33,15635.88
2,Steven Adams,OKC,C,24.0,76.0,76.0,2487.0,6.5,10.3,0.629,...,9.9,1.3,1.3,1.1,1.9,3.1,15.3,22471910.0,5709.33,205535.88
3,Bam Adebayo,MIA,C,20.0,69.0,19.0,1368.0,4.6,8.9,0.512,...,10.0,2.7,0.8,1.1,1.7,3.6,12.6,2490360.0,632.71,22777.56
4,Arron Afflalo,ORL,SG,32.0,53.0,3.0,682.0,3.4,8.6,0.401,...,3.5,1.6,0.2,0.5,1.1,3.0,9.4,2328652.0,591.63,21298.68